### ISSUE TITLE
Maven support?

### ISSUE THREAD

**Issue by elbuo8** [danysantiago/sendgrid-android#1]
Heyo, I got a script that automates this (kinda) with gradle. Wanna give it a shot?

**Comment by danysantiago** [comment]
Sure, whatever makes it a 'add this line in dependencies to use' works.

**Comment by sibelius** [comment]
is it gonna have maven support?

**Comment by danysantiago** [comment]
Working on it, should take around 2 business day to create project so I can deploy: https://issues.sonatype.org/browse/OSSRH-18614

**Comment by danysantiago** [comment]
Its done, updated README.md with info.

**Comment by sibelius** [comment]
thanks
