### ISSUE TITLE
Getting a conflict with the old http files or zip that are already added in project

### ISSUE THREAD

**Issue by git-elliot** [danysantiago/sendgrid-android#5]
Warning:Exception while processing task java.io.IOException: Can't write [/home/paras/AndroidStudioProjects/MeriSafety/app/build/intermediates/transforms/proguard/release/0.jar] (Can't read [/home/paras/android-studio/gradle/caches/modules-2/files-2.1/org.apache.httpcomponents/httpclient/4.3.5/9783d89b8eea20a517a4afc5f979bd2882b54c44/httpclient-4.3.5.jar(;;;;;;**.class)] (Duplicate zip entry [httpclient-4.3.5.jar:org/apache/http/impl/cookie/IgnoreSpecFactory.class]))

**Comment by git-elliot** [comment]
Solved by excluding the conflicting libraries from the dependency.
```

 compile('com.github.danysantiago:sendgrid-android:1', {
        exclude group: 'org.apache.httpcomponents.httpclient-android'
        exclude group: 'org.apache.httpcomponents.httpclient'
    })
```

**Comment by alifarina** [comment]
I am using the above lines of code , but I am getting dex error 
Multiple dex files define Lorg/apache/http/entity/ContentType;

I have tried excluding and adding different options but it doesn't seem to work . A little help here please.

**Comment by alifarina** [comment]
solution can be found here , after a lot of digging and moving back and forth 
https://github.com/alifarina/SendgridAndroid.git
